// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/dod5star-luxury-hero/Current.tsx": () => import("../components/mockups/dod5star-luxury-hero/Current.tsx"),
  "./components/mockups/dod5star-luxury-hero/Luxury.tsx": () => import("../components/mockups/dod5star-luxury-hero/Luxury.tsx")
};
